/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentConfig = IDL.Record({
  'payeeName' : IDL.Text,
  'upiId' : IDL.Text,
  'paymentPurpose' : IDL.Text,
});

export const idlService = IDL.Service({
  'getPaymentConfig' : IDL.Func([], [IDL.Opt(PaymentConfig)], ['query']),
  'setPaymentConfig' : IDL.Func([PaymentConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentConfig = IDL.Record({
    'payeeName' : IDL.Text,
    'upiId' : IDL.Text,
    'paymentPurpose' : IDL.Text,
  });
  
  return IDL.Service({
    'getPaymentConfig' : IDL.Func([], [IDL.Opt(PaymentConfig)], ['query']),
    'setPaymentConfig' : IDL.Func([PaymentConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };